---
title: "Análisis de Datos Categóricos (SOL3070)"
subtitle: "Clase #2"
author: "<br> Mauricio Bucca<br> Profesor Asistente, Sociología UC"
date: "[github.com/mebucca](https://github.com/mebucca)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["default","default-fonts","gentle-r.css"]
    df_print: default
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: true
      slideNumberFormat: "%current%"
editor_options: 
  chunk_output_type: console
---
class: inverse, center, middle

#Probabilidades (continuación)

---

### Probabilidad condicional

.bold[Probabilidad condicional] es un concepto crucial en teoría de la probabilidad y subyace al propósito principal del análisis de regresión logística.
--
 La probabilidad de un evento A después de que nos enteramos de que se ha producido el evento B se denomina probabilidad condicional de A dado B. Formalmente:

$$\mathbb{P}(A | B)$$
--

Ejemplo:
- Experimento: tirar un dado "justo"
- Espacio muestral, $\Omega: \{1,2,3,4,5,6\}$
- A es el evento de obtener un cuatro o más,  $A: \{4,5,6\}$.
- B es el evento de obtener un número par, $B: \{2,4,6\}$.

Supongamos que tiramos el dado pero no miramos el resultado todavía. Una tercera persona te dice que obtuvimos un número par.

--
.full-width[.content-box-red[
.bold[Pregunta]:
¿cuál es la probabilidad de obtener un cuatro o más una vez que _actualizamos_ nuestro conocimiento sobre el comportamiento del dado?
]
]

---

### Probabilidad condicional

Formalmente, nuestra pregunta se expresa del siguiente modo: $\mathbb{P}(A | B )$. Para calcular esta probabilidad utilizamos la siguiente fórmula:

$$\mathbb{P}(A | B ) = \frac{\mathbb{P}(A,B)}{\mathbb{P}(B)}$$
Intuitivamente, queremos saber en qué proporción de los casos en que B ocurre, A también ocurre. 

---
### Probabilidad condicional

$$\mathbb{P}(A | B ) = \frac{\mathbb{P}(A,B)}{\mathbb{P}(B)}$$

Donde,
- $\mathbb{P}(B)$ es la probabilidad de que B ocurra: obtener un número .bold[par]
- $\mathbb{P}(A,B)$ es la probabilidad  A y B ocurran conjuntamente: obtener un número .bold[par igual o superior a 4]

<br>
--

\begin{align}
\mathbb{P}(A | B ) &= \frac{\mathbb{P}(A,B)}{\mathbb{P}(B)} \\ \\
&= \frac{\mathbb{P}(\text{dado=4 o dado=6}) }{\mathbb{P}(\text{dado=2 o dado=4 o dado=6})} \\ \\
&=  \frac{2/6}{3/6} = \frac{1}{3} \times 2
\end{align}


---
### Probabilidad condicional


.bold[Ejercicio rápido]:

Supongamos que:
- Un 5% de población son mujeres (M) con un estudios universitarios completos (U)
- Las mujeres representan 55% de la población
- Un 20% de la población tiene estudios universitarios completos

--

.full-width[.content-box-red[
.bold[Pregunta]:
1) Cual es la probabilidad de que una mujer tenga estudios universitarios completos?
]
]

--

.full-width[.content-box-blue[
.bold[Respuesta]:

1) 
\begin{align}
\mathbb{P}(U | M) = \frac{\mathbb{P}(U,M)}{\mathbb{P}(M)} = \frac{0.05}{0.55} \approx  0.09
\end{align}
]
]

---

### Probabilidad condicional

.bold[Ejercicio rápido]:

Supongamos que:
- Un 5% de población son mujeres (M) con un estudios universitarios completos (U)
- Las mujeres representan 55% de la población
- Un 20% de la población tiene estudios universitarios completos


.full-width[.content-box-red[
.bold[Pregunta]:
2) Cual es la probabilidad de que una persona con estudios universitarios completos sea mujer?
]
]

--

.full-width[.content-box-blue[
.bold[Respuesta]:

2) 
\begin{align}
\mathbb{P}(M | U) = \frac{\mathbb{P}(U,M)}{\mathbb{P}(U)} = \frac{0.05}{0.2} = 0.25
\end{align}
]
]


---

### Probabilidad condicional

.bold[Ejercicio rápido]:

Supongamos que:
- Un 5% de población son mujeres (M) con un estudios universitarios completos (U)
- Las mujeres representan 55% de la población
- Un 20% de la población tiene estudios universitarios completos


.full-width[.content-box-red[
.bold[Pregunta]:
3) Cual es la probabilidad de que una persona con estudios universitarios completos sea hombre?
]
]

--

.full-width[.content-box-blue[
.bold[Respuesta]:

1) 
\begin{align}
\mathbb{P}(H | U) = \frac{\mathbb{P}(U,H)}{\mathbb{P}(U)} = 1- P(M | U) = 1 - 0.25 = 0.75 
\end{align}
]
]


---
### Probabilidad condicional

.full-width[.content-box-red[
.bold[Bonus]:

4) Cual es la probabilidad de que un hombre tenga estudios universitarios completos?

]
]

.bold[Pista]: En general,
$$ \mathbb{P}(A | B) \neq \mathbb{P}(B | A)  $$
<br>
pero el .bold[Teorema de Bayes] nos dice cómo transformar uno en el otro.


---
### Independencia

Dos eventos A y B son .bold[independientes] cuando la ocurrencia de A no afecta la ocurrencia de B y viceversa. 
--
Independencia es una caso especial de probabilidad condicional: $A \bot B$ si el conocimiento sobre B no cambia nuestro conocimiento sobre A. Formalmente:

$$P(A | B) = P(A) \quad \iff \quad P(B | A) = P(B)$$ 
<br>
--
A partir de esta definición podemos derivar un test matemático de independencia:

<br>

\begin{align}
  &P(A | B) = P(A) \\ \\
  &\frac{P(A,B)}{P(B)} = P(A) \\  \\
  &P(A,B) = P(A)P(B) 
\end{align}

<br>
--
Si dos eventos A y B son independientes entonces debe ser cierto que $P(A,B)=P(A)(B)$.

---
### Independencia

Ejemplo:
- Experimento de lanzar dos monedas justas consecutivamente. 
- A es el evento de obtener una Cara con la primera moneda
- B es el evento de obtener Sello con la segunda moneda. 

.full-width[.content-box-red[
.bold[Pregunta]:
Son A y B dos eventos independientes?
]
]

--

.pull-left[
.full-width[.content-box-blue[
.bold[Sabemos que...]
- $P(A) = P(B) = 1/2$

- $\Omega: \{CC,CS,SC,SS\}$

- $(A,B) = \{CS\}$

- $P(A,B) = 1/4$

]
]
]

--

.pull-right[
.full-width[.content-box-blue[
.bold[Test de independencia]

Si A y B son eventos independientes entonces deberiamos espera que $P(A)P(B) = 1/4$

\begin{align}
P(A)P(B) = \frac{1}{2} \times \frac{1}{2} = \frac{1}{4}
\end{align}
]
]
]

---
class: inverse, center, middle

.huge[
**Hasta la próxima clase. Gracias!**
]

<br>
Mauricio Bucca <br>
https://mebucca.github.io/ <br>
github.com/mebucca




