---
title: "Análisis de Datos Categóricos (SOL3070)"
subtitle: "Clase #0"
author: "<br> Mauricio Bucca<br> Profesor Asistente, Sociología UC"
date: "[github.com/mebucca](https://github.com/mebucca)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["default","default-fonts","gentle-r.css"]
    df_print: default
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: true
      slideNumberFormat: "%current%"
editor_options: 
  chunk_output_type: console
---
class: inverse, center, middle

.huge[
**Presentación del curso**
]

---

## Sobre mi

  - Profesor Asistente, Sociología UC

--

  - Max Weber Postdoctoral Fellow, European University Institute, Firenze
  
  - PhD en Sociología, Cornell University, NY
    - PhD Minor en Estadística, Departamento de Estadística, Cornell University

--

  - Investigación: movilidad social intergeneracional,  desigualdades en el mercado laboral, creencias sobre las desigualdades, métodos cuantitativos.
  
  - Métodos: modelación estadística, estrategias empíricas para inferencia causal, métodos experimentales y computacionales.


---

## Mi visión sobre la enseñanza de métodos cuantitativos


- Los "atajos" perjudican el aprendizaje (ej. "p-value=0.05")

--

- Muchas cosas parecen más difíciles de lo que son (notación, desconocimiento, miedo, etc.)


--

$$\mu = \int xf(x)dx$$
--

.bold[Se pueden aprender]

--


- Cosas aparentemente sencillas son más profundas de lo que parece

$$y_{i} = \alpha + \beta x_{i} + \epsilon_{i}$$
--
$$y_{i} \sim \mathcal{N}(\mu_{i}= \alpha + \beta x_{i}, \quad  \sigma = \bar{\epsilon\epsilon} )$$
--

- Los conceptos teóricos se 







---
## Prerequisitos

<br>

- Familiaridad con manejo de funciones, especialmente logarítmicas y exponenciales. 
  - [Estudio personal (click here)]
  

<br>
--

- Nociones básicas de teoría de la probabilidad
  - .bold[Lo cubriremos en este curso]

<br>
--

- Nociones básicas de estimación e inferencia estadística
  - .bold[Lo cubriremos en este curso]

<br>
--

- Un curso previo en análisis de regresión
  - .bold[Check] 


[Estudio personal (click here)]: https://github.com/mebucca/cda_soc3070/blob/master/pre_calculo.pdf>
---


## Objetivos

Si tuvieramos que resumir este curso en una linea .... 

<br>

--

$$\mathbb{P}(Y=1| \mathbf{X})  =  \frac{e^{\mathbf{X\beta}}}{1 + e^{ \mathbf{X\beta}}}$$
<br>

--

Al final de este curso se espera que el alumno sea capaz de:

- *Entender* el significado esta expresion

- *Manipular* matemáticamente esta expresion

- *Estimar* los parametros ( $\mathbf{\beta}$'s ) de este modelo usando el software estadístico `R` (o `Stata`).

- *Interpretar* sustantivamente los resultados del model estadístico

---


class: inverse, center, middle

.huge[
**Hasta la próxima clase. Gracias!**
]

<br>
Mauricio Bucca <br>
https://mebucca.github.io/ <br>
github.com/mebucca




